[package]
name = "touch-rust"
version = "0.1.0"
authors = ["jelipo <me@jelipo.com>"]
edition = "2018"
description = "Touch the 'Internet'."
license = "MIT"
homepage = "https://github.com/jelipo/touch-rust"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.6.5"
fantasy-util = "0.1.6"
cfb-mode = "0.5.0"
aes-gcm = "0.7.0"
hkdf = "0.9.0"
sha-1 = "0.9.1"
base64 = "0.13.0"
hex = "0.4.2"
ring = "0.16.15"
md-5 = "0.9.1"