[package]
name = "touch-rust"
version = "0.1.0"
authors = ["jelipo <me@jelipo.com>"]
edition = "2018"
description = "Touch the 'Internet'."
license = "MIT"
homepage = "https://github.com/jelipo/touch-rust"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfb-mode = "0.6.0"
aes-gcm = "0.8.0"
chacha20poly1305 = "0.7.1"

async-std = "1.7.0"
fantasy-util = "0.1.6"

hkdf = "0.10.0"
sha-1 = "0.9.2"
base64 = "0.13.0"
hex = "0.4.2"
md-5 = "0.9.1"

async-trait = "0.1.41"